name: "\U0001F680 New feature proposal"
description: 提出要添加的新功能。
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您对该项目的兴趣并花时间填写此功能报告！
  - type: textarea
    id: feature-description
    attributes:
      description: 如果您打算为此问题提交 PR，请在描述中告诉我们。 谢谢！
      placeholder: 清晰简洁的问题描述
    validations:
      required: true
